package model;
// Generated 05/11/2015 20:36:48 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ComponenteCursoItemOferta generated by hbm2java
 */
@Entity
//gerar as sequencias para os seriais (auto_increment)
@SequenceGenerator(name = "componentecursoitemoferta_seq", sequenceName = "componentecursoitemoferta_seq_no_banco", allocationSize = 1, initialValue = 1)
@Table(name = "componente_curso_item_oferta", schema = "public")
public class ComponenteCursoItemOferta implements java.io.Serializable {

    private int id;
    private ComponenteCurso componenteCurso;
    private ItemOferta itemOferta;

    public ComponenteCursoItemOferta() {
    }

    public ComponenteCursoItemOferta(int id, ComponenteCurso componenteCurso, ItemOferta itemoferta) {
        this.id = id;
        this.componenteCurso = componenteCurso;
        this.itemOferta = itemoferta;
    }

    @Id
    @GeneratedValue(generator = "componentecursoitemoferta_seq")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "componentecurso_id", nullable = false)
    public ComponenteCurso getComponenteCurso() {
        return this.componenteCurso;
    }

    public void setComponenteCurso(ComponenteCurso componenteCurso) {
        this.componenteCurso = componenteCurso;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "itemoferta_id", nullable = false)
    public ItemOferta getItemOferta() {
        return this.itemOferta;
    }

    public void setItemOferta(ItemOferta itemOferta) {
        this.itemOferta = itemOferta;
    }

}
