package model;
// Generated 05/11/2015 20:36:48 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComponenteCursoItemOferta generated by hbm2java
 */
@Entity

@Table(name="componentecursoitemoferta"
    ,schema="public"
)
public class ComponenteCursoItemOferta  implements java.io.Serializable {


     private int id;
     private ComponenteCurso componentecurso;
     private ItemOferta itemoferta;

    public ComponenteCursoItemOferta() {
    }

    public ComponenteCursoItemOferta(int id, ComponenteCurso componentecurso, ItemOferta itemoferta) {
       this.id = id;
       this.componentecurso = componentecurso;
       this.itemoferta = itemoferta;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="componentecurso_id", nullable=false)
    public ComponenteCurso getComponenteCurso() {
        return this.componentecurso;
    }
    
    public void setComponenteCurso(ComponenteCurso componentecurso) {
        this.componentecurso = componentecurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="itemoferta_id", nullable=false)
    public ItemOferta getItemOferta() {
        return this.itemoferta;
    }
    
    public void setItemOferta(ItemOferta itemoferta) {
        this.itemoferta = itemoferta;
    }




}


