package model;
// Generated 27/09/2015 11:19:22 by Hibernate Tools 4.3.1

import dao.DAOCurso;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * Curso generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "curso_seq", sequenceName = "curso_seq_no_banco", allocationSize = 1, initialValue = 1)
@Table(name = "curso", schema = "public"
)
public class Curso implements java.io.Serializable {

    //<editor-fold defaultstate="collapsed" desc="Variaveis">
    private int id;
    private Docente docente;
    private String cod;
    private String nome;
    private int numeroDeSemestres;
    private Set componenteCursos = new HashSet(0);
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Construtores">
    public Curso() {
    }

    public Curso(int id, Docente docente, String cod, String nome) {
        this.id = id;
        this.docente = docente;
        this.cod = cod;
        this.nome = nome;
    }

//</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Getters e Setters">
    @Id
    @GeneratedValue(generator = "curso_seq")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "coordenador_id", nullable = true)
    public Docente getDocente() {
        return this.docente;
    }

    public void setDocente(Docente docente) {
        this.docente = docente;
    }

    @Column(name = "cod", nullable = false, length = 30)
    public String getCod() {
        return this.cod;
    }

    public void setCod(String cod) {
        this.cod = cod;
    }

    @Column(name = "nome", nullable = false, length = 80)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "numerodesemestre", nullable = false)
    public int getNumeroDeSemestres() {
        return numeroDeSemestres;
    }

    public void setNumeroDeSemestres(int numeroDeSemestres) {
        this.numeroDeSemestres = numeroDeSemestres;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "curso", cascade = CascadeType.REMOVE)
    @OnDelete(action = OnDeleteAction.CASCADE)
    public Set<ComponenteCurso> getComponenteCursos() {
        return this.componenteCursos;
    }

    public void setComponenteCursos(Set componenteCursos) {
        this.componenteCursos = componenteCursos;
    }

//</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Métodos de Equals e HashCode">
//    @Override
//    public int hashCode() {
//        int hash = 3;
//        hash = 53 * hash + this.id;
//        hash = 53 * hash + Objects.hashCode(this.docente);
//        hash = 53 * hash + Objects.hashCode(this.cod);
//        hash = 53 * hash + Objects.hashCode(this.nome);
//        return hash;
//    }
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Curso other = (Curso) obj;
        if (this.id != other.id) {
            return false;
        }
        if (!Objects.equals(this.cod, other.cod)) {
            return false;
        }
        return true;
    }

//</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Metodos de Persistencia">
    static public boolean salvar(Curso c) {
        return DAOCurso.salvar(c);
    }

    static public ArrayList<Curso> consultar() {
        return DAOCurso.consultar();
    }

    static public Curso consultar(int id) {
        return DAOCurso.consultar(id);
    }

    static public boolean alterar(Curso d) {
        return DAOCurso.alterar(d);
    }

    static public boolean excluir(Curso d) {
        return DAOCurso.excluir(d);
    }

    static public int count() {
        return DAOCurso.count();
    }
//</editor-fold>

}
