package model;
// Generated 27/09/2015 11:19:22 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DocenteItemOferta generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "docenteitemoferta_seq", sequenceName = "docenteitemoferta_seq_no_banco", allocationSize = 1, initialValue = 1) 
@Table(name = "docente_item_oferta", schema = "public"
)
public class DocenteItemOferta implements java.io.Serializable {

    private int id;
    private Docente docente;
    private ItemOferta itemOferta;
    private short creditos;

    public DocenteItemOferta() {
    }

    public DocenteItemOferta(int id, Docente docente, ItemOferta itemOferta, short creditos) {
        this.id = id;
        this.docente = docente;
        this.itemOferta = itemOferta;
        this.creditos = creditos;
    }

    @Id
    @GeneratedValue(generator = "docenteitemoferta_seq")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "docente_id", nullable = false)
    public Docente getDocente() {
        return this.docente;
    }

    public void setDocente(Docente docente) {
        this.docente = docente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_oferta_id", nullable = false)
    public ItemOferta getItemOferta() {
        return this.itemOferta;
    }

    public void setItemOferta(ItemOferta itemOferta) {
        this.itemOferta = itemOferta;
    }

    @Column(name = "creditos", nullable = false)
    public short getCreditos() {
        return this.creditos;
    }

    public void setCreditos(short creditos) {
        this.creditos = creditos;
    }

}
