package model;
// Generated 27/09/2015 11:19:22 by Hibernate Tools 4.3.1

import dao.DAODocente;
import excecoes.IntegridadeReferencialException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * Docente generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "docente_seq", sequenceName = "docente_seq_no_banco", allocationSize = 1, initialValue = 1)
@Table(name = "docente", schema = "public"
)
public class Docente implements java.io.Serializable {

    //<editor-fold defaultstate="collapsed" desc="Variaveis">
    private int id;
    private Concurso concurso;
    private String nome;
    private boolean atuaposgraduacao;
    private String linklattes;
    private String emailinstitucional;
    private int siape;
    private String areagraduacao;
    private String login;
    private String senha;
    private int nivel = 0;
    private Set<DocenteItemOferta> docenteItemOfertas = new HashSet(0);
    private Set<InstrucaoDocente> instrucaoDocentes = new HashSet(0);
    private Set<Curso> cursos = new HashSet(0);
    private Set<Preferencia> preferencias = new HashSet(0);
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Construtores">
    public Docente() {
    }

    public Docente(int id, Concurso concurso, String nome, boolean atuaposgraduacao, String linklattes, String emailinstitucional, int siape, String areagraduacao, String login, String senha) {
        this.id = id;
        this.concurso = concurso;
        this.nome = nome;
        this.atuaposgraduacao = atuaposgraduacao;
        this.linklattes = linklattes;
        this.emailinstitucional = emailinstitucional;
        this.siape = siape;
        this.areagraduacao = areagraduacao;
        this.login = login;
        this.senha = senha;
    }

    public Docente(int id, Concurso concurso, String nome, boolean atuaposgraduacao, String linklattes, String emailinstitucional, int siape, String areagraduacao, String login, String senha, Set docenteItemOfertas, Set instrucaoDocentes, Set cursos, Set preferencias) {
        this.id = id;
        this.concurso = concurso;
        this.nome = nome;
        this.atuaposgraduacao = atuaposgraduacao;
        this.linklattes = linklattes;
        this.emailinstitucional = emailinstitucional;
        this.siape = siape;
        this.areagraduacao = areagraduacao;
        this.login = login;
        this.senha = senha;
        this.docenteItemOfertas = docenteItemOfertas;
        this.instrucaoDocentes = instrucaoDocentes;
        this.cursos = cursos;
        this.preferencias = preferencias;
    }
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Getters e Setters">
    @Id
    @GeneratedValue(generator = "docente_seq")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "concurso_id", nullable = true)
    public Concurso getConcurso() {
        return this.concurso;
    }

    public void setConcurso(Concurso concurso) {
        this.concurso = concurso;
    }

    @Column(name = "nome", nullable = false, length = 50)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "atuaposgraduacao", nullable = false)
    public boolean isAtuaposgraduacao() {
        return this.atuaposgraduacao;
    }

    public void setAtuaposgraduacao(boolean atuaposgraduacao) {
        this.atuaposgraduacao = atuaposgraduacao;
    }

    @Column(name = "linklattes", nullable = true, length = 50)
    public String getLinklattes() {
        return this.linklattes;
    }

    public void setLinklattes(String linklattes) {
        this.linklattes = linklattes;
    }

    @Column(name = "emailinstitucional", nullable = false, length = 60)
    public String getEmailinstitucional() {
        return this.emailinstitucional;
    }

    public void setEmailinstitucional(String emailinstitucional) {
        this.emailinstitucional = emailinstitucional;
    }

    @Column(name = "siape", nullable = false)
    public int getSiape() {
        return this.siape;
    }

    public void setSiape(int siape) {
        this.siape = siape;
    }

    @Column(name = "areagraduacao", nullable = true, length = 80)
    public String getAreagraduacao() {
        return this.areagraduacao;
    }

    public void setAreagraduacao(String areagraduacao) {
        this.areagraduacao = areagraduacao;
    }

    @Column(name = "login", nullable = true, length = 30)
    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    @Column(name = "senha", nullable = false, length = 30)
    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
    public Set<DocenteItemOferta> getDocenteItemOfertas() {
        return this.docenteItemOfertas;
    }

    public void setDocenteItemOfertas(Set docenteItemOfertas) {
        this.docenteItemOfertas = docenteItemOfertas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
    public Set<InstrucaoDocente> getInstrucaoDocentes() {
        return this.instrucaoDocentes;
    }

    public void setInstrucaoDocentes(Set instrucaoDocentes) {
        this.instrucaoDocentes = instrucaoDocentes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
    public Set<Curso> getCursos() {
        return this.cursos;
    }

    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
    public Set<Preferencia> getPreferencias() {
        return this.preferencias;
    }

    public void setPreferencias(Set preferencias) {
        this.preferencias = preferencias;
    }

    @Column(name = "nivel", nullable = false, columnDefinition = "int default 0")
    public int getNivel() {
        return nivel;
    }

    public void setNivel(int nivel) {
        this.nivel = nivel;
    }

//</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Métodos Equals e HashCode">
    @Override
    public int hashCode() {
        int hash = 7;
        //hash = 17 * hash + this.id;
        hash = 17 * hash + this.siape;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Docente other = (Docente) obj;
        if (this.id != other.id) {
            return false;
        }
        if (this.siape != other.siape) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return this.getNome();
    }

//</editor-fold>
//    public Autenticavel autenticar(String login, String senha) {
//        return DAODocente.autenticar(login, senha);
//
//    }
    //<editor-fold defaultstate="collapsed" desc="Persistencia">
    static public boolean salvar(Docente d) {
        return DAODocente.salvar(d);
    }

    static public ArrayList<Docente> consultar() {
        return DAODocente.consultar();
    }
    
    static public Docente consultar(int id) {
        return DAODocente.consultar(id);
    }

    static public Collection<Docente> consultar(String nome) {
        return DAODocente.consultar(nome);
    }

    static public boolean alterar(Docente d) {
        return DAODocente.alterar(d);
    }

    static public boolean excluir(Docente d) throws IntegridadeReferencialException {
        return DAODocente.excluir(d);
    }

    static public int count() {
        return DAODocente.count();
    }
//</editor-fold>
    
    public ArrayList<Docente> buscarCoordenadores(){
        ArrayList<Docente> docentes = DAODocente.consultar();
        ArrayList<Docente> coordenadores = new ArrayList<>();
        
        for (Docente docente : docentes) {
            if(docente.getNivel() != 0){
                coordenadores.add(docente);
            }
        }
        return coordenadores;
    }

}
