package model;
// Generated 27/09/2015 11:19:22 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * InstrucaoDocente generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "InstrucaoDocente_seq", sequenceName = "InstrucaoDocente_seq_no_banco", allocationSize = 1, initialValue = 1) 
@Table(name = "instrucao_docente", schema = "public"
)
public class InstrucaoDocente implements java.io.Serializable {

    private int id;
    private Docente docente;
    private Instrucao instrucao;

    public InstrucaoDocente() {
    }


    @Id
    @GeneratedValue(generator = "InstrucaoDocente_seq")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "docente_id", nullable = false)
    public Docente getDocente() {
        return this.docente;
    }

    public void setDocente(Docente docente) {
        this.docente = docente;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "instrucao_id", nullable = false)
    public Instrucao getInstrucao() {
        return this.instrucao;
    }

    public void setInstrucao(Instrucao instrucao) {
        this.instrucao = instrucao;
    }

}
