package model;
// Generated 27/09/2015 11:19:22 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Instrucao generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "instrucao_seq", sequenceName = "instrucao_seq_no_banco", allocationSize = 1, initialValue = 1) 
@Table(name = "instrucao", schema = "public"
)
public class Instrucao implements java.io.Serializable {

    private int id;
    private Oferta oferta;
    private String descricao;
    private Set instrucaoDocentes = new HashSet(0);
    private Set instrucaoComponenteCurriculars = new HashSet(0);

    public Instrucao() {
    }

    public Instrucao(int id, Oferta oferta, String descricao) {
        this.id = id;
        this.oferta = oferta;
        this.descricao = descricao;
    }

    public Instrucao(int id, Oferta oferta, String descricao, Set instrucaoDocentes, Set instrucaoComponenteCurriculars) {
        this.id = id;
        this.oferta = oferta;
        this.descricao = descricao;
        this.instrucaoDocentes = instrucaoDocentes;
        this.instrucaoComponenteCurriculars = instrucaoComponenteCurriculars;
    }

    @Id
    @GeneratedValue(generator = "instrucao_seq")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "oferta_id", nullable = false)
    public Oferta getOferta() {
        return this.oferta;
    }

    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }

    @Column(name = "descricao", nullable = false)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "instrucao")
    public Set<InstrucaoDocente> getInstrucaoDocentes() {
        return this.instrucaoDocentes;
    }

    public void setInstrucaoDocentes(Set instrucaoDocentes) {
        this.instrucaoDocentes = instrucaoDocentes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "instrucao")
    public Set<InstrucaoComponenteCurricular> getInstrucaoComponenteCurriculars() {
        return this.instrucaoComponenteCurriculars;
    }

    public void setInstrucaoComponenteCurriculars(Set instrucaoComponenteCurriculars) {
        this.instrucaoComponenteCurriculars = instrucaoComponenteCurriculars;
    }

}
