package model;
// Generated 27/09/2015 11:19:22 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * InstrucaoComponenteCurricular generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "instrucaocomponentecurricular_seq", sequenceName = "instrucaocomponentecurricular_seq_no_banco", allocationSize = 1, initialValue = 1) 
@Table(name = "instrucao_componente_curricular", schema = "public"
)
public class InstrucaoComponenteCurricular implements java.io.Serializable {

    private int id;
    private ComponenteCurricular componenteCurricular;
    private Instrucao instrucao;

    public InstrucaoComponenteCurricular() {
    }

    public InstrucaoComponenteCurricular(int id, ComponenteCurricular componenteCurricular, Instrucao instrucao) {
        this.id = id;
        this.componenteCurricular = componenteCurricular;
        this.instrucao = instrucao;
    }

    @Id
    @GeneratedValue(generator = "instrucaocomponentecurricular_seq")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "componente_curricular_id", nullable = false)
    public ComponenteCurricular getComponenteCurricular() {
        return this.componenteCurricular;
    }

    public void setComponenteCurricular(ComponenteCurricular componenteCurricular) {
        this.componenteCurricular = componenteCurricular;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "instrucao_id", nullable = false)
    public Instrucao getInstrucao() {
        return this.instrucao;
    }

    public void setInstrucao(Instrucao instrucao) {
        this.instrucao = instrucao;
    }

}
