package model;
// Generated 27/09/2015 11:19:22 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ItemOferta generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "itemoferta_seq", sequenceName = "itemoferta_seq_no_banco", allocationSize = 1, initialValue = 1) 
@Table(name = "item_oferta", schema = "public"
)
public class ItemOferta implements java.io.Serializable {

    private int id;
    private ComponenteCurso componenteCurso;
    private ItemOferta itemOferta;
    private Oferta oferta;
    private short vagasOfertadas;
    private short vagasReservadas;
    private Set itemOfertas = new HashSet(0);
    private Set docenteItemOfertas = new HashSet(0);

    public ItemOferta() {
    }

  

    @Id
    @GeneratedValue(generator = "itemoferta_seq")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "componente_curso_id", nullable = false)
    public ComponenteCurso getComponenteCurso() {
        return this.componenteCurso;
    }

    public void setComponenteCurso(ComponenteCurso componenteCurso) {
        this.componenteCurso = componenteCurso;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_oferta_id")
    public ItemOferta getItemOferta() {
        return this.itemOferta;
    }

    public void setItemOferta(ItemOferta itemOferta) {
        this.itemOferta = itemOferta;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "oferta_id", nullable = false)
    public Oferta getOferta() {
        return this.oferta;
    }

    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }

    @Column(name = "vagas_ofertadas", nullable = false)
    public short getVagasOfertadas() {
        return this.vagasOfertadas;
    }

    public void setVagasOfertadas(short vagasOfertadas) {
        this.vagasOfertadas = vagasOfertadas;
    }

    @Column(name = "vagas_reservadas", nullable = false)
    public short getVagasReservadas() {
        return this.vagasReservadas;
    }

    public void setVagasReservadas(short vagasReservadas) {
        this.vagasReservadas = vagasReservadas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "itemOferta")
    public Set<ItemOferta> getItemOfertas() {
        return this.itemOfertas;
    }

    public void setItemOfertas(Set itemOfertas) {
        this.itemOfertas = itemOfertas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "itemOferta")
    public Set<DocenteItemOferta> getDocenteItemOfertas() {
        return this.docenteItemOfertas;
    }

    public void setDocenteItemOfertas(Set docenteItemOfertas) {
        this.docenteItemOfertas = docenteItemOfertas;
    }

}
