package model;
// Generated 27/09/2015 11:19:22 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ItemOferta generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "itemoferta_seq", sequenceName = "itemoferta_seq_no_banco", allocationSize = 1, initialValue = 1)
@Table(name = "item_oferta", schema = "public"
)
public class ItemOferta implements java.io.Serializable {

    private int id;
    private Oferta oferta;
    private Set componenteCursoItemOfertas = new HashSet(0);
    private Set docenteItemOfertas = new HashSet(0);

    public ItemOferta() {
    }

    @Id
    @GeneratedValue(generator = "itemoferta_seq")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "oferta_id", nullable = false)
    public Oferta getOferta() {
        return this.oferta;
    }

    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "itemOferta")
    public Set<ComponenteCursoItemOferta> getComponenteCursoItemOfertas() {
        return this.componenteCursoItemOfertas;
    }

    public void setComponenteCursoItemOfertas(Set componentecursoitemofertas) {
        this.componenteCursoItemOfertas = componentecursoitemofertas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "itemOferta")
    public Set<DocenteItemOferta> getDocenteItemOfertas() {
        return this.docenteItemOfertas;
    }

    public void setDocenteItemOfertas(Set docenteItemOfertas) {
        this.docenteItemOfertas = docenteItemOfertas;
    }

}
