package model;
// Generated 27/09/2015 11:19:22 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Preferencia generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "preferencia_seq", sequenceName = "preferencia_seq_no_banco", allocationSize = 1, initialValue = 1)
@Table(name = "preferencia", schema = "public"
)
public class Preferencia implements java.io.Serializable {

    private int id;
    private ComponenteCurricular componenteCurricular;
    private Docente docente;
    private Integer graupreferencia;

    public Preferencia() {
    }

 

    @Id
    @GeneratedValue(generator = "preferencia_seq")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "componente_curricular_id", nullable = false)
    public ComponenteCurricular getComponenteCurricular() {
        return this.componenteCurricular;
    }

    public void setComponenteCurricular(ComponenteCurricular componenteCurricular) {
        this.componenteCurricular = componenteCurricular;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "docente_id", nullable = false)
    public Docente getDocente() {
        return this.docente;
    }

    public void setDocente(Docente docente) {
        this.docente = docente;
    }

    @Column(name = "graupreferencia")
    public Integer getGraupreferencia() {
        return this.graupreferencia;
    }

    public void setGraupreferencia(Integer graupreferencia) {
        this.graupreferencia = graupreferencia;
    }

}
